/**
 * Created by hyamaji on 9/1/2015.
 */
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/helpdesk');
var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function (callback) {
    console.log('MongoDB connection success.');
});

// Schema
var ticketSchema = mongoose.Schema({
    userName: String,
    department: String,
    problemType: String,
    priority: String,
    title: String,
    description: String,
    created_at: { type: Date, default: new Date()},
    status: {type: String, default: 'open'},
});

// Compiling Schema into Model
var Ticket = mongoose.model('Ticket', ticketSchema);

var TicketData =
    [
        {
            "created_at": "Tue May 05 2015 11:54:22 GMT+0000 (UTC)",
            "status": "open",
            "description": "Non dolore non minim aute occaecat magna deserunt mollit voluptate. Ipsum minim duis ea labore irure laboris fugiat enim sint in ut ea occaecat irure. Labore et enim irure veniam commodo ad labore Lorem enim. Eu dolor exercitation cupidatat esse id excepteur irure consequat velit.",
            "title": "tempor ea nulla quis minim esse enim id",
            "priority": "High",
            "problemType": "Network",
            "department": "HR",
            "userName": "Albert Blankenship",
            "ticketId": 00008,
        },
        {
            "created_at": "Sun Jan 25 2015 14:19:54 GMT+0000 (UTC)",
            "status": "open",
            "description": "Quis esse veniam ullamco dolor deserunt nostrud. Mollit officia dolore ullamco enim nisi enim elit fugiat sunt ullamco exercitation anim in veniam. Aliquip minim ut commodo dolore amet cillum nostrud Lorem enim. Aliqua officia aute minim eiusmod sunt adipisicing non sunt. Pariatur qui esse eu excepteur pariatur sint irure laborum ea officia ipsum. Enim duis reprehenderit cillum sit esse eu nulla pariatur culpa. Ad id magna et laboris nulla anim ut fugiat reprehenderit in.",
            "title": "nisi ea mollit ex culpa cupidatat eu est",
            "priority": "High",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Gregory Fox",
            "ticketId": 101,
        },
        {
            "created_at": "Tue Aug 19 2014 19:56:33 GMT+0000 (UTC)",
            "status": "open",
            "description": "Eu enim deserunt voluptate duis duis incididunt commodo in laborum ad anim irure excepteur aute. Eu culpa consequat esse proident ipsum Lorem minim sint tempor quis cupidatat est. Cupidatat aliqua et id mollit. Eiusmod est aliquip anim veniam culpa ea sit pariatur ad sit sit. Commodo ad officia elit cupidatat consectetur culpa ex sint nisi.",
            "title": "esse Lorem consequat elit duis culpa nostrud cillum",
            "priority": "Low",
            "problemType": "Network",
            "department": "HR",
            "userName": "Becker Jordan",
            "ticketId": 102,
        },
        {
            "created_at": "Fri Jul 17 2015 17:30:30 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ea culpa exercitation et fugiat pariatur fugiat labore elit incididunt aliquip non cupidatat excepteur. Do consequat mollit quis nulla. Magna velit deserunt mollit duis nulla enim aute eiusmod. Tempor adipisicing nisi nulla sunt.",
            "title": "qui culpa nisi enim ipsum anim excepteur velit",
            "priority": "Medium",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Marsh Snow",
            "ticketId": 103,
        },
        {
            "created_at": "Sun Apr 05 2015 07:52:35 GMT+0000 (UTC)",
            "status": "open",
            "description": "Adipisicing sunt reprehenderit Lorem consequat id ad ea dolore aute. Velit aute aliquip quis dolor Lorem pariatur do culpa cillum elit culpa cillum pariatur. Elit nulla esse deserunt proident pariatur. Laboris ullamco et qui laborum quis eiusmod laboris qui. In nostrud veniam adipisicing do reprehenderit ut dolore in elit velit elit in et mollit. Do commodo exercitation id deserunt anim nulla nisi nisi culpa reprehenderit.",
            "title": "ad minim nostrud voluptate nostrud culpa non laborum",
            "priority": "Low",
            "problemType": "Network",
            "department": "Marketing",
            "userName": "Herman Gould",
        },
        {
            "created_at": "Fri Jul 24 2015 16:44:22 GMT+0000 (UTC)",
            "status": "open",
            "description": "Fugiat anim culpa reprehenderit et amet aute minim ut sunt ut aliqua magna. Ad officia tempor non voluptate ex tempor aliquip exercitation nulla id. Mollit incididunt qui et aliquip minim. Dolore minim eiusmod tempor in magna. Minim non consectetur ullamco adipisicing proident nostrud. Voluptate ex cillum tempor eiusmod et veniam ex adipisicing minim id magna.",
            "title": "consectetur eiusmod esse velit irure qui exercitation laboris",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Clemons Cross",
            "ticketId": 105,
        },
        {
            "created_at": "Mon Jan 05 2015 06:27:44 GMT+0000 (UTC)",
            "status": "open",
            "description": "Minim amet quis veniam culpa irure eu. Sint ex ex aute voluptate fugiat ullamco ipsum cupidatat. Dolor quis nulla qui et voluptate incididunt dolor non excepteur incididunt aute. Officia Lorem Lorem non in occaecat.",
            "title": "laboris nostrud consequat exercitation pariatur laborum consequat exercitation",
            "priority": "Medium",
            "problemType": "Software",
            "department": "IT",
            "userName": "Pamela Schroeder",
            "ticketId": 106,
        },
        {
            "created_at": "Wed Jul 23 2014 12:16:53 GMT+0000 (UTC)",
            "status": "open",
            "description": "Eiusmod occaecat pariatur pariatur qui eu duis mollit occaecat. Fugiat amet in tempor non tempor reprehenderit. Excepteur reprehenderit ullamco sint mollit ex est ea officia veniam. Ipsum do esse amet in ullamco veniam mollit id. Nisi laboris ea elit est id cupidatat commodo esse eiusmod ad enim ut labore commodo. Quis ea irure minim eiusmod mollit labore veniam elit laboris consectetur mollit sunt.",
            "title": "nostrud anim eu sunt laborum incididunt deserunt irure",
            "priority": "High",
            "problemType": "Network",
            "department": "IT",
            "userName": "Whitaker Hutchinson",
            "ticketId": 107,
        },
        {
            "created_at": "Tue Jan 20 2015 23:42:24 GMT+0000 (UTC)",
            "status": "open",
            "description": "Nostrud adipisicing veniam irure tempor sint aliqua eu deserunt reprehenderit tempor aliqua est ipsum tempor. Laborum excepteur amet magna quis ullamco Lorem aliqua laboris. Ex enim minim voluptate sunt ea do cillum qui veniam occaecat aliqua dolore. Nisi qui culpa non in dolor dolore reprehenderit cillum cillum. Enim incididunt amet ullamco nostrud in non nulla nisi ea cupidatat anim reprehenderit.",
            "title": "dolore pariatur excepteur pariatur laborum sit exercitation incididunt",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Tonia Clemons",
            "ticketId": 108,
        },
        {
            "created_at": "Mon Mar 23 2015 00:38:28 GMT+0000 (UTC)",
            "status": "open",
            "description": "Aliqua velit occaecat do nulla eiusmod do anim do Lorem reprehenderit deserunt. Nisi elit culpa occaecat ipsum ullamco ipsum nulla reprehenderit anim anim. Officia culpa exercitation qui proident exercitation et voluptate. Incididunt minim id ut laboris anim non laboris. Est ea quis quis velit eu ad officia pariatur elit.",
            "title": "aute sit esse ut ex veniam labore reprehenderit",
            "priority": "High",
            "problemType": "Network",
            "department": "Marketing",
            "userName": "Queen Mueller",
            "ticketId": 109,
        },
        {
            "created_at": "Tue May 20 2014 04:07:41 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolore eiusmod cupidatat mollit est. Ad tempor in id dolore tempor exercitation ea id consequat ex. Incididunt in aute amet dolor consequat cillum excepteur consequat et in cillum cupidatat ipsum.",
            "title": "anim ut non proident pariatur ullamco sint reprehenderit",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Essie Morrison",
            "ticketId": 110,
            "_id": 10
        },
        {
            "created_at": "Mon Oct 06 2014 17:55:57 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ullamco mollit ea culpa Lorem non labore nostrud sint do anim. Laboris pariatur mollit sint ipsum fugiat excepteur ullamco est nostrud consequat velit. Duis veniam id aliqua non laborum Lorem in.",
            "title": "qui laborum excepteur ad dolore et laboris sit",
            "priority": "High",
            "problemType": "Software",
            "department": "HR",
            "userName": "Maddox Wynn",
            "ticketId": 111,
            "_id": 11
        },
        {
            "created_at": "Thu Feb 13 2014 00:14:33 GMT+0000 (UTC)",
            "status": "open",
            "description": "Eu cupidatat irure dolore aliquip sit excepteur sint irure nisi minim est nostrud. Quis labore amet est ullamco ea quis eiusmod est non fugiat consequat. In occaecat ullamco ea est velit ad labore sit in anim. Veniam culpa tempor aute cillum dolore enim in. Fugiat mollit veniam occaecat do reprehenderit ullamco ut ad consequat nisi. Eu ex nulla aliquip eiusmod excepteur consectetur sunt sint reprehenderit sunt ea officia minim cillum. Fugiat ad ex magna dolor sint incididunt consectetur.",
            "title": "culpa duis Lorem laboris excepteur minim mollit esse",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Leticia Gentry",
            "ticketId": 112,
            "_id": 12
        },
        {
            "created_at": "Wed Jun 03 2015 16:32:26 GMT+0000 (UTC)",
            "status": "open",
            "description": "Fugiat reprehenderit nostrud pariatur ullamco excepteur eu nostrud. Do labore nisi fugiat eu est ad cupidatat ad velit eu aute officia. Consectetur do ex labore eiusmod consequat sint ut consectetur laboris deserunt enim deserunt enim. Minim cupidatat est cillum aliqua amet id exercitation proident eu laboris amet. Irure consectetur voluptate pariatur non aliqua labore officia exercitation anim. Proident eiusmod id ipsum nisi.",
            "title": "sit minim veniam et incididunt qui sunt quis",
            "priority": "Medium",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Jennie Hebert",
            "ticketId": 113,
            "_id": 13
        },
        {
            "created_at": "Thu Jan 16 2014 03:13:40 GMT+0000 (UTC)",
            "status": "open",
            "description": "Lorem culpa deserunt consectetur proident enim. Dolore velit velit ipsum labore pariatur culpa cillum minim id nisi id ullamco. Culpa ut tempor in commodo aliqua aliquip sit enim pariatur amet. Nulla ipsum elit excepteur anim eiusmod ut exercitation adipisicing reprehenderit ipsum. Est magna aute aute esse dolore sunt deserunt sunt.",
            "title": "ullamco in est nisi irure do Lorem commodo",
            "priority": "Low",
            "problemType": "Network",
            "department": "IT",
            "userName": "Allyson Merrill",
            "ticketId": 114,
            "_id": 14
        },
        {
            "created_at": "Mon Mar 16 2015 23:39:35 GMT+0000 (UTC)",
            "status": "open",
            "description": "Et aliqua minim excepteur ea quis esse culpa et exercitation sint fugiat ullamco fugiat. Aute minim ipsum ad ad esse et dolor Lorem. Sint nulla quis aliqua et est ipsum sit et.",
            "title": "id enim voluptate magna nisi ut amet nulla",
            "priority": "Low",
            "problemType": "Software",
            "department": "IT",
            "userName": "Eleanor Patton",
            "ticketId": 115,
            "_id": 15
        },
        {
            "created_at": "Tue Jan 06 2015 11:19:06 GMT+0000 (UTC)",
            "status": "open",
            "description": "Veniam enim occaecat nulla pariatur laborum nulla exercitation ullamco velit mollit nulla enim. Ullamco culpa consectetur aute esse magna aliqua ex qui labore proident aliqua. Enim reprehenderit est exercitation ullamco amet et ipsum incididunt.",
            "title": "cillum fugiat anim quis laborum cillum nisi do",
            "priority": "High",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Bridgett Larson",
            "ticketId": 116,
            "_id": 16
        },
        {
            "created_at": "Sat May 23 2015 20:02:31 GMT+0000 (UTC)",
            "status": "open",
            "description": "In incididunt amet ea cillum reprehenderit ad officia est tempor voluptate labore. Excepteur nulla ad id consectetur enim velit sunt. Consectetur ipsum reprehenderit esse anim mollit commodo id fugiat minim. Fugiat quis officia et velit aliqua nulla. Aliquip adipisicing ullamco enim nulla sint ullamco. Et irure nostrud exercitation qui sunt eu amet.",
            "title": "minim esse sint aliqua qui officia in ipsum",
            "priority": "Medium",
            "problemType": "Software",
            "department": "HR",
            "userName": "Jones Graham",
            "ticketId": 117,
            "_id": 17
        },
        {
            "created_at": "Thu Aug 27 2015 08:36:54 GMT+0000 (UTC)",
            "status": "open",
            "description": "Exercitation laborum consectetur qui duis aliquip aute cillum culpa culpa occaecat elit dolor consectetur. Incididunt laboris incididunt Lorem tempor. Ex ea adipisicing magna duis do. Lorem ad cillum sunt mollit dolor do eu aliqua consequat. Nostrud incididunt sunt irure incididunt sit excepteur excepteur magna. Laborum adipisicing do adipisicing occaecat nulla et dolore irure. Excepteur dolore non nostrud esse consectetur quis.",
            "title": "irure esse consequat culpa commodo ad ea aliquip",
            "priority": "Low",
            "problemType": "Software",
            "department": "HR",
            "userName": "Conway Spence",
            "ticketId": 118,
            "_id": 18
        },
        {
            "created_at": "Thu May 01 2014 01:25:26 GMT+0000 (UTC)",
            "status": "open",
            "description": "Duis est laborum amet enim. Et nostrud eu reprehenderit eu sunt sint nisi tempor id dolore dolore amet quis. Laborum sint veniam ipsum pariatur mollit quis laborum sit culpa deserunt magna. Do magna irure culpa eiusmod. Magna nisi dolore mollit voluptate dolor non pariatur sit eiusmod proident. Culpa eiusmod excepteur cupidatat ad duis sint qui eiusmod do qui. Do in esse anim cillum ullamco irure veniam cillum adipisicing.",
            "title": "eiusmod et labore non est laboris pariatur quis",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Elizabeth Maddox",
            "ticketId": 119,
            "_id": 19
        },
        {
            "created_at": "Sat Feb 21 2015 12:46:58 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolor adipisicing velit duis ullamco et laboris enim aute aliquip. Magna nisi nulla magna sint nulla voluptate non qui ipsum anim. Pariatur deserunt est eiusmod ea sit dolore mollit. Cupidatat nisi duis aliqua tempor incididunt ex Lorem eiusmod do id. Tempor deserunt consectetur aliqua aliquip velit proident adipisicing. Ex nisi id ut veniam magna minim amet laboris Lorem nisi deserunt.",
            "title": "nulla esse dolor nulla culpa tempor voluptate voluptate",
            "priority": "Medium",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Leta Soto",
            "ticketId": 120,
            "_id": 20
        },
        {
            "created_at": "Tue Jan 06 2015 20:53:36 GMT+0000 (UTC)",
            "status": "open",
            "description": "Occaecat et quis nulla ea ex reprehenderit anim velit cillum esse ipsum cillum. Reprehenderit exercitation labore consectetur amet exercitation dolor amet eu deserunt elit aliqua. Velit commodo cillum cupidatat qui consectetur. Aliqua mollit fugiat aliqua exercitation. Fugiat dolore quis excepteur culpa incididunt est sint occaecat cupidatat sint. Ipsum amet commodo veniam eu tempor exercitation non.",
            "title": "ipsum enim ad quis non nostrud laboris nulla",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Claire Hooper",
            "ticketId": 121,
            "_id": 21
        },
        {
            "created_at": "Tue Feb 25 2014 03:19:34 GMT+0000 (UTC)",
            "status": "open",
            "description": "Sit excepteur aliqua Lorem ipsum. Amet quis sit occaecat laboris culpa minim fugiat anim duis est. Tempor sunt laborum proident id incididunt commodo id officia non. Voluptate fugiat deserunt magna aute minim veniam tempor ex. Aliqua irure dolore est dolore. Eu cillum sit proident elit fugiat sint ipsum tempor id. Sit tempor pariatur ut tempor.",
            "title": "quis officia ut occaecat velit incididunt deserunt enim",
            "priority": "High",
            "problemType": "Network",
            "department": "Marketing",
            "userName": "Travis Flores",
            "ticketId": 122,
            "_id": 22
        },
        {
            "created_at": "Mon Aug 17 2015 10:49:19 GMT+0000 (UTC)",
            "status": "open",
            "description": "Aliquip qui adipisicing nulla nisi dolore dolor elit elit magna ipsum. Sint ad ex do aliqua. Minim nulla amet anim tempor reprehenderit veniam eiusmod occaecat dolor. Aute cupidatat cupidatat ut pariatur irure id. Ipsum culpa ut et sint adipisicing eiusmod ea irure deserunt Lorem ullamco dolore. Cupidatat ex ex do aliquip laborum non. Anim labore pariatur et adipisicing mollit quis dolore id voluptate anim tempor anim mollit.",
            "title": "ad quis veniam in occaecat aute voluptate ipsum",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Nicholson Watkins",
            "ticketId": 123,
            "_id": 23
        },
        {
            "created_at": "Fri Jul 10 2015 13:41:22 GMT+0000 (UTC)",
            "status": "open",
            "description": "Excepteur aliquip commodo ea elit. Deserunt ea deserunt nulla esse aliqua mollit nulla deserunt in reprehenderit. Cupidatat ad deserunt nostrud ipsum labore nisi exercitation consequat eiusmod et. Enim sint cupidatat deserunt elit in id dolore. Ullamco qui ut occaecat reprehenderit exercitation cupidatat. Cupidatat labore duis exercitation eu esse et duis sunt. Laborum ipsum proident fugiat laboris voluptate do sit ad excepteur consequat sunt sint sit.",
            "title": "consectetur nostrud consectetur cupidatat cupidatat aliqua non laborum",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Lottie Ochoa",
            "ticketId": 124,
            "_id": 24
        },
        {
            "created_at": "Sun Aug 09 2015 02:05:23 GMT+0000 (UTC)",
            "status": "open",
            "description": "Nostrud reprehenderit dolor consequat ex laborum nisi qui ut exercitation exercitation. Fugiat magna esse deserunt adipisicing occaecat. Proident quis reprehenderit eiusmod mollit et do non aute eu aute enim tempor. Nulla irure sit laborum qui elit aliquip labore id labore magna do velit ut et.",
            "title": "aute quis do elit ut incididunt tempor ut",
            "priority": "Low",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Ana Jimenez",
            "ticketId": 125,
            "_id": 25
        },
        {
            "created_at": "Sun Apr 26 2015 02:20:53 GMT+0000 (UTC)",
            "status": "open",
            "description": "Qui amet irure fugiat exercitation. Mollit eu duis ad sit nisi enim aliquip magna ex qui. Consequat dolor proident sit aute ipsum eiusmod irure est nulla sit. Magna sint elit amet esse deserunt non consequat eu Lorem ullamco laborum cupidatat. Deserunt do et dolore consequat labore reprehenderit cillum aliquip dolor sit aliqua laboris. Amet ipsum dolore ut laborum.",
            "title": "sit aliquip esse esse nostrud id cillum sit",
            "priority": "High",
            "problemType": "Software",
            "department": "HR",
            "userName": "Darlene Mcbride",
            "ticketId": 126,
            "_id": 26
        },
        {
            "created_at": "Mon Jan 05 2015 17:52:47 GMT+0000 (UTC)",
            "status": "open",
            "description": "Anim ullamco elit ea labore ex excepteur fugiat pariatur duis dolor nulla quis velit dolore. Occaecat laboris ullamco quis ea laboris id duis sint sit. Tempor ea exercitation excepteur esse. Ipsum minim excepteur magna commodo ea sunt esse non incididunt cupidatat. Consectetur deserunt nisi in reprehenderit aliqua fugiat laboris ut quis laboris cillum consectetur do cillum. Sint ut aliqua consectetur nulla duis sint cupidatat tempor ad velit. Ut laboris cillum nulla pariatur aliquip elit incididunt ad ullamco deserunt amet labore ex duis.",
            "title": "laborum duis non irure deserunt nulla laborum incididunt",
            "priority": "Medium",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Patrica Gay",
            "ticketId": 127,
            "_id": 27
        },
        {
            "created_at": "Fri Apr 24 2015 23:53:35 GMT+0000 (UTC)",
            "status": "open",
            "description": "Mollit elit consequat labore id officia incididunt ea voluptate culpa sit non sunt. Sit cillum in nulla esse ex proident id cupidatat voluptate occaecat irure ullamco labore proident. Fugiat ullamco excepteur fugiat anim labore enim commodo. Deserunt eiusmod sint ad sunt et enim excepteur est non cupidatat sunt laborum. Ullamco amet deserunt veniam ullamco ex nisi non sint et culpa quis laborum. Exercitation sit voluptate irure sit excepteur mollit proident culpa aliquip. Esse et nulla irure esse sunt.",
            "title": "ullamco mollit eu est aliquip et elit pariatur",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Judith Hoffman",
            "ticketId": 128,
            "_id": 28
        },
        {
            "created_at": "Sun Sep 07 2014 00:28:07 GMT+0000 (UTC)",
            "status": "open",
            "description": "Consectetur quis aliquip labore dolore consequat cillum labore pariatur occaecat sint exercitation. Ullamco pariatur duis et et labore reprehenderit deserunt ipsum cillum mollit aute in. Dolor deserunt occaecat nulla sunt voluptate magna consequat et magna voluptate elit eu elit. Sunt duis minim ut nostrud nulla ullamco quis.",
            "title": "Lorem occaecat sit cupidatat velit ullamco dolor voluptate",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Bailey Dixon",
            "ticketId": 129,
            "_id": 29
        },
        {
            "created_at": "Sun Feb 02 2014 23:41:32 GMT+0000 (UTC)",
            "status": "open",
            "description": "Cupidatat voluptate do laboris consequat aute. Sunt elit in et laboris in ut ipsum nulla. Ad consectetur ut voluptate nisi dolor laboris dolore. Labore in excepteur anim ullamco proident.",
            "title": "Lorem laboris commodo cupidatat ut ipsum duis minim",
            "priority": "High",
            "problemType": "Network",
            "department": "IT",
            "userName": "Bowers Hays",
            "ticketId": 130,
            "_id": 30
        },
        {
            "created_at": "Fri May 23 2014 10:39:35 GMT+0000 (UTC)",
            "status": "open",
            "description": "Culpa cillum exercitation ut esse ut et fugiat nostrud voluptate deserunt ipsum tempor. Incididunt voluptate minim esse cillum nisi incididunt cillum. Fugiat sunt deserunt et in sunt ipsum incididunt officia enim excepteur irure consectetur. Reprehenderit occaecat eu id irure. Aute pariatur mollit dolore cupidatat minim ad id magna velit sint aliquip sint pariatur. Pariatur est dolore veniam est officia nostrud do aute aliquip. Id elit incididunt exercitation ut excepteur aute voluptate id amet cillum.",
            "title": "amet cupidatat Lorem commodo consectetur sint eu culpa",
            "priority": "Medium",
            "problemType": "Software",
            "department": "HR",
            "userName": "Celina Kirkland",
            "ticketId": 131,
            "_id": 31
        },
        {
            "created_at": "Mon Mar 09 2015 13:54:28 GMT+0000 (UTC)",
            "status": "open",
            "description": "Excepteur et ipsum dolore anim dolore adipisicing minim amet laborum. Ullamco enim duis incididunt reprehenderit commodo labore laboris tempor. Eu nisi nisi do nostrud veniam quis et.",
            "title": "enim officia laboris ut anim ut dolor ea",
            "priority": "High",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Glenna Mejia",
            "ticketId": 132,
            "_id": 32
        },
        {
            "created_at": "Thu Apr 09 2015 18:27:56 GMT+0000 (UTC)",
            "status": "open",
            "description": "Deserunt irure amet labore esse sint id sunt non ea ea culpa dolor. Irure fugiat ipsum ut amet cillum enim cillum in labore magna ipsum aliqua. Irure ipsum reprehenderit nostrud duis Lorem aliqua velit anim do et aliqua in. Eiusmod amet aliqua commodo ut ut irure culpa sunt cupidatat exercitation. Reprehenderit laborum fugiat magna incididunt et non id ea aliquip veniam occaecat. Id do non occaecat et do nulla adipisicing nisi pariatur officia deserunt nulla ea.",
            "title": "sint dolore proident dolore elit adipisicing deserunt elit",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Roman Holmes",
            "ticketId": 133,
            "_id": 33
        },
        {
            "created_at": "Mon Jun 02 2014 21:43:21 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolore laboris ipsum eiusmod ut elit mollit anim ad eiusmod ullamco. Deserunt labore nulla eu velit pariatur proident eu amet qui. Reprehenderit qui consectetur irure non ullamco consequat nulla ut culpa.",
            "title": "culpa dolor incididunt do veniam minim nulla pariatur",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Kerr Estes",
            "ticketId": 134,
            "_id": 34
        },
        {
            "created_at": "Fri Jun 27 2014 17:49:20 GMT+0000 (UTC)",
            "status": "open",
            "description": "Pariatur consequat commodo sunt cillum pariatur irure non aute aliquip quis id dolore. Officia consectetur et sint incididunt laborum adipisicing proident ullamco esse magna minim et. Eu aute reprehenderit aliquip excepteur nisi labore. Laboris ipsum dolor commodo amet adipisicing anim non consectetur aute occaecat et voluptate proident. In quis nulla qui irure consectetur consequat. Consectetur proident occaecat ea aute consequat sunt dolor Lorem consectetur et sit. Labore ex anim officia consequat do sit Lorem velit laborum voluptate occaecat.",
            "title": "labore exercitation pariatur irure non et velit veniam",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Bender Hickman",
            "ticketId": 135,
            "_id": 35
        },
        {
            "created_at": "Mon Jun 29 2015 20:43:46 GMT+0000 (UTC)",
            "status": "open",
            "description": "Veniam irure veniam labore labore velit sunt irure deserunt ut. Irure quis officia amet id. Anim reprehenderit velit fugiat duis aliquip sit non aute sint tempor veniam. Velit aute enim ullamco quis culpa. Quis laborum pariatur in tempor laboris non irure ut mollit. Ad culpa anim sunt eiusmod ea in sit.",
            "title": "ad non sint irure esse nulla est ex",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Wise Bass",
            "ticketId": 136,
            "_id": 36
        },
        {
            "created_at": "Sun Jun 15 2014 09:07:07 GMT+0000 (UTC)",
            "status": "open",
            "description": "Elit fugiat aute tempor ad amet qui ea est consequat dolore consectetur elit exercitation. Exercitation sit est excepteur fugiat. Qui aliqua aliqua enim labore cillum. Cillum et aliquip sunt nulla eiusmod exercitation sint sit dolor laborum labore nulla.",
            "title": "aliquip aute veniam consectetur adipisicing duis est fugiat",
            "priority": "Low",
            "problemType": "Software",
            "department": "IT",
            "userName": "Melinda Coleman",
            "ticketId": 137,
            "_id": 37
        },
        {
            "created_at": "Mon Apr 13 2015 02:00:16 GMT+0000 (UTC)",
            "status": "open",
            "description": "Consectetur proident sint ut cillum. Mollit magna nostrud officia do duis pariatur id aute elit. Duis magna cillum commodo exercitation fugiat aliqua. Est voluptate culpa ut aute nulla et consectetur nulla enim cupidatat aliquip. Minim do enim aliqua eiusmod aute elit fugiat non. Magna est laboris incididunt incididunt ad deserunt adipisicing non id. Reprehenderit est elit laborum duis ad fugiat.",
            "title": "mollit irure ad laboris proident consectetur quis sunt",
            "priority": "Low",
            "problemType": "Network",
            "department": "IT",
            "userName": "Wilder Hahn",
            "ticketId": 138,
            "_id": 38
        },
        {
            "created_at": "Sun Apr 20 2014 01:23:32 GMT+0000 (UTC)",
            "status": "open",
            "description": "Eu eu qui anim dolor sunt reprehenderit. Amet eiusmod laborum commodo id. Aliquip veniam ipsum fugiat labore sunt in ut deserunt et minim fugiat adipisicing aliqua.",
            "title": "quis tempor pariatur laborum qui incididunt velit labore",
            "priority": "High",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Hill Jefferson",
            "ticketId": 139,
            "_id": 39
        },
        {
            "created_at": "Mon Dec 08 2014 07:59:52 GMT+0000 (UTC)",
            "status": "open",
            "description": "Laboris culpa laboris commodo aute cupidatat velit. Qui fugiat amet deserunt est veniam. Veniam officia enim elit exercitation labore enim aliqua eu nostrud qui nisi ullamco ut.",
            "title": "exercitation labore fugiat officia et non aute eiusmod",
            "priority": "Medium",
            "problemType": "Network",
            "department": "IT",
            "userName": "Winters Vincent",
            "ticketId": 140,
            "_id": 40
        },
        {
            "created_at": "Tue Sep 16 2014 08:44:34 GMT+0000 (UTC)",
            "status": "open",
            "description": "Aliqua magna sunt duis est dolor deserunt laborum consequat esse. Dolor ipsum duis consequat irure tempor mollit eu dolore irure ut nisi sit. Enim id adipisicing ullamco id ut consequat proident deserunt. Proident sit ipsum eiusmod nisi culpa eiusmod exercitation irure reprehenderit enim fugiat Lorem. Exercitation magna anim esse aute pariatur exercitation labore adipisicing dolore esse pariatur ut.",
            "title": "aute deserunt officia qui officia ad tempor consequat",
            "priority": "High",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Callahan Castillo",
            "ticketId": 141,
            "_id": 41
        },
        {
            "created_at": "Wed Aug 13 2014 02:14:31 GMT+0000 (UTC)",
            "status": "open",
            "description": "Officia aute irure elit sunt esse dolore sit in. Labore cupidatat ullamco nulla exercitation aliqua dolore ullamco sint occaecat elit. Anim est duis nulla officia aute voluptate minim nisi culpa. Ut cupidatat aliquip in ipsum cupidatat amet mollit. Nostrud dolore sit excepteur sit veniam nulla duis exercitation ex qui dolore deserunt eu. Dolor labore id nulla id dolor ex dolore duis. Duis commodo irure occaecat occaecat ad voluptate proident nostrud sit proident.",
            "title": "id dolore cillum velit ut ut nostrud nisi",
            "priority": "Medium",
            "problemType": "Network",
            "department": "Marketing",
            "userName": "Sasha Pickett",
            "ticketId": 142,
            "_id": 42
        },
        {
            "created_at": "Tue Oct 14 2014 21:45:44 GMT+0000 (UTC)",
            "status": "open",
            "description": "Occaecat adipisicing in proident magna deserunt non. In irure fugiat enim ipsum. Excepteur nulla Lorem consectetur nostrud sint magna aliqua irure do ea ut eu magna voluptate. Eu ipsum dolore id ullamco irure non nisi velit excepteur cillum anim veniam ipsum.",
            "title": "labore anim consectetur nostrud ipsum ullamco veniam qui",
            "priority": "Medium",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Sparks Thornton",
            "ticketId": 143,
            "_id": 43
        },
        {
            "created_at": "Wed Aug 12 2015 18:14:08 GMT+0000 (UTC)",
            "status": "open",
            "description": "Esse qui ad voluptate cillum consequat. Cupidatat qui esse id ea sit in labore incididunt duis nisi cillum. Commodo dolore proident et et pariatur et sunt commodo.",
            "title": "minim cupidatat nostrud Lorem pariatur non ullamco non",
            "priority": "Medium",
            "problemType": "Software",
            "department": "IT",
            "userName": "Jefferson Preston",
            "ticketId": 144,
            "_id": 44
        },
        {
            "created_at": "Fri Feb 07 2014 15:07:21 GMT+0000 (UTC)",
            "status": "open",
            "description": "Sunt sunt proident consectetur laborum duis enim minim pariatur quis adipisicing. Cillum fugiat exercitation aliquip nisi. Eu dolor sint ut elit. Eiusmod esse officia ut occaecat aliquip. Ea laborum duis cillum deserunt velit dolor. Minim incididunt aliquip veniam ea commodo sunt incididunt proident sint sint tempor consequat. Adipisicing minim occaecat Lorem laboris non nostrud aliqua aliqua magna amet.",
            "title": "sint laborum cupidatat amet non deserunt ullamco ipsum",
            "priority": "High",
            "problemType": "Software",
            "department": "IT",
            "userName": "Medina Woods",
            "ticketId": 145,
            "_id": 45
        },
        {
            "created_at": "Thu Sep 11 2014 17:23:42 GMT+0000 (UTC)",
            "status": "open",
            "description": "Anim pariatur proident nisi fugiat officia nostrud amet qui quis. Nostrud duis adipisicing adipisicing ex sunt est aliqua. Voluptate laborum dolore anim occaecat. Laboris cillum elit ex enim duis velit ut aliqua ea ipsum aliqua aliqua dolore. Cupidatat anim commodo velit duis cupidatat laborum. Ex duis et eu voluptate deserunt. Laborum et non Lorem culpa cupidatat amet.",
            "title": "id non reprehenderit commodo sit qui nulla amet",
            "priority": "High",
            "problemType": "Software",
            "department": "IT",
            "userName": "Jenkins Blanchard",
            "ticketId": 146,
            "_id": 46
        },
        {
            "created_at": "Sat Dec 20 2014 21:48:03 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolor officia ullamco fugiat in. Qui incididunt velit exercitation nulla elit esse nostrud nisi esse est ipsum. Consectetur duis cupidatat cupidatat sit cillum cillum dolore. Enim elit aliquip ea est amet qui Lorem ut enim nulla. Non eu culpa amet officia esse nulla et nostrud veniam mollit in magna occaecat eu.",
            "title": "aliqua ad incididunt in dolor nostrud occaecat cillum",
            "priority": "Low",
            "problemType": "Network",
            "department": "HR",
            "userName": "Fry Chandler",
            "ticketId": 147,
            "_id": 47
        },
        {
            "created_at": "Sat Feb 07 2015 07:38:56 GMT+0000 (UTC)",
            "status": "open",
            "description": "Lorem irure nisi eu officia. Aute laboris velit officia aliqua cillum minim enim est Lorem irure est. Ipsum magna ea et veniam fugiat pariatur elit sint fugiat Lorem. In nostrud ex enim eu quis consequat et. Dolore eu sunt dolor eiusmod. Est tempor enim et labore excepteur culpa sint. Est Lorem exercitation do pariatur irure sint tempor deserunt nisi et.",
            "title": "ut elit consequat quis anim esse id ex",
            "priority": "High",
            "problemType": "Software",
            "department": "IT",
            "userName": "Candice Joseph",
            "ticketId": 148,
            "_id": 48
        },
        {
            "created_at": "Tue Apr 08 2014 17:05:18 GMT+0000 (UTC)",
            "status": "open",
            "description": "Fugiat exercitation ut consectetur irure. Magna anim consequat proident minim sint amet. Reprehenderit deserunt dolor ex aliquip reprehenderit nisi id. Duis aliqua ipsum Lorem esse in. Elit sint nostrud ipsum laborum cillum consequat in ad commodo voluptate elit est occaecat enim. Exercitation eiusmod ut laborum qui. Nulla consequat mollit dolore ex sit ex ea mollit.",
            "title": "laborum et consectetur laboris aliqua sint exercitation adipisicing",
            "priority": "Medium",
            "problemType": "Software",
            "department": "IT",
            "userName": "Krista Hoover",
            "ticketId": 149,
            "_id": 49
        },
        {
            "created_at": "Tue Sep 16 2014 00:40:50 GMT+0000 (UTC)",
            "status": "open",
            "description": "Duis et sint ut dolore qui dolore consequat et. Laborum ea reprehenderit exercitation est nostrud consectetur ipsum nisi aliquip cupidatat proident. Consectetur voluptate magna proident Lorem. Sunt ex voluptate ipsum in sit commodo non dolore labore ullamco excepteur ut. Et non ea eiusmod enim Lorem culpa voluptate dolor duis non duis amet reprehenderit quis.",
            "title": "qui cillum qui sit do sunt exercitation officia",
            "priority": "Medium",
            "problemType": "Software",
            "department": "HR",
            "userName": "Ashley Pennington",
            "ticketId": 150,
            "_id": 50
        },
        {
            "created_at": "Fri Apr 04 2014 12:54:50 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ea amet ex voluptate et sunt officia fugiat labore laboris aute pariatur nostrud irure deserunt. Cillum exercitation proident aliquip laborum eu ea fugiat eu incididunt elit laboris ex ipsum exercitation. Dolor officia occaecat commodo adipisicing. Deserunt voluptate culpa aute veniam eu deserunt pariatur anim non sit in proident sunt adipisicing.",
            "title": "duis consequat esse laboris voluptate sint excepteur ut",
            "priority": "High",
            "problemType": "Software",
            "department": "IT",
            "userName": "Lott Cherry",
            "ticketId": 151,
            "_id": 51
        },
        {
            "created_at": "Wed Mar 26 2014 07:45:35 GMT+0000 (UTC)",
            "status": "open",
            "description": "Proident officia officia deserunt incididunt id do sit nostrud laboris dolor exercitation do est. Voluptate minim velit non et consectetur anim irure dolor consequat sit. Proident eiusmod nostrud nisi Lorem ea anim enim aliquip proident. Veniam voluptate consequat dolor laborum eiusmod reprehenderit minim eu culpa est reprehenderit tempor. Fugiat do deserunt irure elit id pariatur nulla ullamco minim.",
            "title": "voluptate tempor reprehenderit eiusmod eiusmod eu laboris veniam",
            "priority": "Low",
            "problemType": "Software",
            "department": "HR",
            "userName": "Ellen Brown",
            "ticketId": 152,
            "_id": 52
        },
        {
            "created_at": "Tue Dec 09 2014 04:35:25 GMT+0000 (UTC)",
            "status": "open",
            "description": "Magna ad cupidatat commodo laborum aliquip est fugiat ea aute tempor commodo dolor. Do incididunt nisi eiusmod duis fugiat cupidatat eiusmod voluptate proident cupidatat nostrud. Deserunt laboris cillum dolor Lorem consequat elit deserunt nulla dolor enim. Proident aliquip incididunt ex elit pariatur minim esse velit excepteur sit laboris dolor. Proident velit aute aliqua minim ut.",
            "title": "commodo voluptate dolore velit eu cupidatat irure dolore",
            "priority": "High",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Carson Tucker",
            "ticketId": 153,
            "_id": 53
        },
        {
            "created_at": "Tue Aug 05 2014 20:21:23 GMT+0000 (UTC)",
            "status": "open",
            "description": "Est commodo culpa velit qui eiusmod velit nisi labore. Nostrud duis elit duis eiusmod sint Lorem eiusmod sit consequat aute duis eiusmod eiusmod. Est eu fugiat laborum laborum Lorem est labore et tempor dolor adipisicing. Esse eiusmod culpa id deserunt excepteur velit. Labore est voluptate aliquip cillum occaecat. Anim amet Lorem ex esse elit commodo.",
            "title": "Lorem consectetur nisi esse incididunt dolore Lorem eu",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Yvette Rivera",
            "ticketId": 154,
            "_id": 54
        },
        {
            "created_at": "Sat Feb 28 2015 20:46:38 GMT+0000 (UTC)",
            "status": "open",
            "description": "Quis qui deserunt occaecat amet et nisi sunt officia minim. Non esse in consectetur pariatur. Nulla ea Lorem proident nostrud dolore excepteur aute laboris nisi. Id proident tempor commodo eu magna proident. Nulla ipsum mollit consequat dolor et commodo ea excepteur cillum. Deserunt aliquip sunt Lorem sint proident fugiat. Reprehenderit Lorem voluptate duis Lorem pariatur laboris esse aliquip.",
            "title": "id sint anim excepteur ipsum ea dolore pariatur",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Randi Lowery",
            "ticketId": 155,
            "_id": 55
        },
        {
            "created_at": "Mon Aug 24 2015 17:53:36 GMT+0000 (UTC)",
            "status": "open",
            "description": "Aliquip id laboris veniam ullamco proident ex culpa. Quis aliquip commodo non consectetur ut ea esse sint proident sint id consectetur ullamco esse. Laboris aliqua minim laboris aliquip eiusmod ipsum excepteur officia sunt do incididunt exercitation ut. In ad do velit adipisicing cillum in velit Lorem et. Aute qui aute exercitation consequat aliqua pariatur. Tempor labore cupidatat consectetur et aliquip occaecat magna qui sit incididunt aute reprehenderit proident Lorem. Elit labore minim commodo magna exercitation consectetur laboris.",
            "title": "esse cillum nulla reprehenderit ipsum incididunt est reprehenderit",
            "priority": "Medium",
            "problemType": "Software",
            "department": "IT",
            "userName": "Olson Price",
            "ticketId": 156,
            "_id": 56
        },
        {
            "created_at": "Sat Nov 15 2014 06:16:45 GMT+0000 (UTC)",
            "status": "open",
            "description": "Sint ad et laboris aliquip commodo eiusmod elit minim dolore. Eu labore id commodo est. Aliqua officia esse amet deserunt dolore tempor elit. Aliquip ut occaecat cillum occaecat sunt reprehenderit velit officia laborum ex irure consequat non. In cupidatat culpa adipisicing dolore occaecat sunt culpa. Ipsum Lorem qui cupidatat minim eu culpa et ea nisi. Fugiat duis commodo ullamco amet incididunt Lorem.",
            "title": "tempor aute exercitation proident et dolor deserunt cillum",
            "priority": "High",
            "problemType": "Software",
            "department": "HR",
            "userName": "Consuelo Stout",
            "ticketId": 157,
            "_id": 57
        },
        {
            "created_at": "Fri Sep 04 2015 02:34:37 GMT+0000 (UTC)",
            "status": "open",
            "description": "Enim anim quis proident eu mollit pariatur consectetur sint ipsum deserunt pariatur ea ad. Fugiat consequat magna occaecat in ipsum velit. Aute ea fugiat aute enim sit quis est.",
            "title": "fugiat dolor proident minim mollit eu ipsum tempor",
            "priority": "High",
            "problemType": "Network",
            "department": "IT",
            "userName": "Spence Copeland",
            "ticketId": 158,
            "_id": 58
        },
        {
            "created_at": "Sun Mar 09 2014 21:34:04 GMT+0000 (UTC)",
            "status": "open",
            "description": "In sunt sunt commodo ipsum irure enim sunt. Excepteur proident ut commodo ullamco ipsum velit magna occaecat qui. Voluptate sunt cillum esse mollit do ea est tempor aute anim labore ad pariatur.",
            "title": "anim eiusmod incididunt consectetur non eiusmod consectetur do",
            "priority": "Medium",
            "problemType": "Network",
            "department": "HR",
            "userName": "Rutledge Browning",
            "ticketId": 159,
            "_id": 59
        },
        {
            "created_at": "Wed Mar 19 2014 04:33:03 GMT+0000 (UTC)",
            "status": "open",
            "description": "Sunt magna in elit reprehenderit cupidatat occaecat magna non. Non sint ad in occaecat in quis. Officia labore nostrud laboris ut eiusmod proident et aute consectetur tempor. Velit sit qui sunt est consequat nisi esse occaecat. Proident et laborum irure irure labore eiusmod veniam.",
            "title": "labore sit amet eiusmod velit quis aliqua nostrud",
            "priority": "Low",
            "problemType": "Software",
            "department": "IT",
            "userName": "Gena Ortega",
            "ticketId": 160,
            "_id": 60
        },
        {
            "created_at": "Sat Aug 16 2014 17:53:53 GMT+0000 (UTC)",
            "status": "open",
            "description": "Consequat cupidatat fugiat magna ad anim elit ut sint minim consectetur officia irure velit veniam. Duis velit et nulla quis tempor dolor. Aliqua ad commodo esse adipisicing incididunt deserunt ipsum velit dolor nulla. Anim adipisicing incididunt ad aute veniam. Culpa exercitation esse irure sunt ipsum tempor anim consequat commodo ipsum velit pariatur. Incididunt incididunt anim veniam excepteur officia nostrud adipisicing dolore cillum commodo eiusmod. Ea ut adipisicing pariatur commodo elit culpa tempor.",
            "title": "proident aliqua aliquip incididunt consectetur ullamco irure incididunt",
            "priority": "High",
            "problemType": "Network",
            "department": "HR",
            "userName": "Ester Baldwin",
            "ticketId": 161,
            "_id": 61
        },
        {
            "created_at": "Sun Jul 06 2014 07:28:40 GMT+0000 (UTC)",
            "status": "open",
            "description": "Sunt excepteur esse nulla dolore consequat elit duis Lorem ea pariatur magna proident. Est ea nisi cillum proident veniam aliquip quis ex culpa nostrud consequat amet. Consectetur non non consequat fugiat labore tempor commodo Lorem labore cupidatat. Laborum laboris eu anim mollit ea velit eu excepteur commodo. Voluptate veniam pariatur cillum deserunt aliquip nostrud culpa veniam tempor eu nostrud culpa.",
            "title": "occaecat officia consequat consequat id nisi magna minim",
            "priority": "Low",
            "problemType": "Network",
            "department": "HR",
            "userName": "Klein Henson",
            "ticketId": 162,
            "_id": 62
        },
        {
            "created_at": "Thu Apr 10 2014 04:45:05 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolore elit quis exercitation occaecat incididunt commodo eiusmod nisi ullamco commodo et. Ea in commodo qui do veniam laborum nostrud eu elit deserunt Lorem. Minim enim incididunt Lorem mollit cupidatat laboris mollit qui fugiat elit labore mollit reprehenderit dolore. Eiusmod aliqua cillum eiusmod adipisicing est incididunt ullamco non dolor. Eu sint ullamco esse aliqua sint sit.",
            "title": "deserunt magna ullamco officia est aute pariatur et",
            "priority": "Medium",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Allison Velasquez",
            "ticketId": 163,
            "_id": 63
        },
        {
            "created_at": "Wed Jan 21 2015 09:45:13 GMT+0000 (UTC)",
            "status": "open",
            "description": "Amet magna dolore nisi consectetur dolor laboris enim occaecat laborum tempor et proident. Adipisicing ut id do consequat qui adipisicing. Occaecat ea magna in anim aliquip ullamco nostrud. Labore qui ut nostrud minim adipisicing officia cupidatat laboris duis dolor nostrud non sunt.",
            "title": "anim aliqua sint laborum velit occaecat quis do",
            "priority": "High",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Beulah Mathis",
            "ticketId": 164,
            "_id": 64
        },
        {
            "created_at": "Wed Mar 18 2015 16:50:47 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolore eiusmod proident amet sint elit sit. Commodo enim culpa sunt ipsum irure elit ut eiusmod ut voluptate sunt reprehenderit in. Ullamco cupidatat consequat enim veniam minim irure proident minim do sunt ad id elit. Proident irure eiusmod duis laboris anim voluptate fugiat consequat exercitation voluptate. Ullamco consequat adipisicing enim veniam dolor.",
            "title": "ad proident tempor cillum ipsum ad consectetur minim",
            "priority": "High",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Durham Moon",
            "ticketId": 165,
            "_id": 65
        },
        {
            "created_at": "Tue Jul 08 2014 22:20:56 GMT+0000 (UTC)",
            "status": "open",
            "description": "Sint id ipsum ullamco exercitation ipsum aliquip officia occaecat. Pariatur do ex nulla non nostrud aliquip occaecat aliquip consequat in anim laborum quis labore. Sint sit velit proident culpa eu anim nisi deserunt nulla cupidatat nostrud minim esse quis. Enim id nulla ea excepteur cillum irure aliqua mollit ea dolor aute minim adipisicing elit. Commodo proident amet consequat voluptate. Fugiat cupidatat cillum deserunt est culpa do occaecat ipsum nisi laboris ullamco ea.",
            "title": "non nisi quis veniam cillum enim fugiat et",
            "priority": "High",
            "problemType": "Network",
            "department": "IT",
            "userName": "Kramer Rodgers",
            "ticketId": 166,
            "_id": 66
        },
        {
            "created_at": "Mon Jul 06 2015 18:12:25 GMT+0000 (UTC)",
            "status": "open",
            "description": "Veniam ipsum sint ullamco aliqua excepteur labore duis laborum est. Ut adipisicing Lorem ex nulla dolor. Ea est incididunt excepteur mollit irure deserunt nostrud non occaecat est deserunt elit. Nisi enim fugiat pariatur excepteur. Aliqua minim laborum incididunt officia excepteur occaecat. Nostrud dolore aute reprehenderit in laboris id ad sint eu.",
            "title": "non consectetur exercitation nulla est duis duis occaecat",
            "priority": "Medium",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Stacy Conway",
            "ticketId": 167,
            "_id": 67
        },
        {
            "created_at": "Sat Jul 18 2015 13:20:13 GMT+0000 (UTC)",
            "status": "open",
            "description": "Pariatur amet deserunt aute et commodo laborum. Officia qui sint laboris consequat adipisicing esse occaecat anim sunt ad magna anim aliquip quis. Velit exercitation nulla dolore incididunt laboris in anim pariatur adipisicing sunt duis.",
            "title": "magna fugiat duis tempor minim tempor aliquip anim",
            "priority": "Medium",
            "problemType": "Software",
            "department": "HR",
            "userName": "Leonor Ingram",
            "ticketId": 168,
            "_id": 68
        },
        {
            "created_at": "Tue Oct 07 2014 13:02:16 GMT+0000 (UTC)",
            "status": "open",
            "description": "Excepteur nulla cillum sit laboris cupidatat laborum fugiat in esse eu aliquip velit in. Est aute esse mollit laboris Lorem. Ipsum adipisicing eiusmod ullamco commodo proident. Quis occaecat aliquip duis est eiusmod incididunt proident nisi cillum ea deserunt anim ut. Dolor sunt ipsum officia dolor velit ex voluptate exercitation quis nisi. Est magna deserunt officia deserunt qui. Velit cupidatat ex velit ea excepteur mollit cillum aute deserunt velit aliquip elit.",
            "title": "minim magna irure anim enim adipisicing labore culpa",
            "priority": "Low",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Cherry Beasley",
            "ticketId": 169,
            "_id": 69
        },
        {
            "created_at": "Sat May 16 2015 00:44:47 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolor culpa officia incididunt fugiat eu labore laboris nostrud ad non proident et. Aliqua sunt et enim voluptate sunt nulla enim duis. Cillum Lorem proident occaecat mollit sint. Dolor pariatur adipisicing nostrud minim veniam consequat non consequat. Exercitation quis ullamco labore mollit adipisicing sunt ut enim. Id deserunt quis sunt culpa ad fugiat. Nostrud ea elit officia et id commodo cillum adipisicing est.",
            "title": "dolor qui esse adipisicing exercitation qui commodo voluptate",
            "priority": "High",
            "problemType": "Network",
            "department": "IT",
            "userName": "Jacobs Blackwell",
            "ticketId": 170,
            "_id": 70
        },
        {
            "created_at": "Wed Mar 19 2014 19:50:20 GMT+0000 (UTC)",
            "status": "open",
            "description": "Cupidatat quis irure dolore eu. Cupidatat in ipsum labore deserunt. Irure in mollit laborum fugiat quis dolor dolor incididunt voluptate pariatur nisi amet fugiat.",
            "title": "id sint sunt ullamco nulla consequat Lorem consequat",
            "priority": "Medium",
            "problemType": "Software",
            "department": "HR",
            "userName": "Wendy Fuentes",
            "ticketId": 171,
            "_id": 71
        },
        {
            "created_at": "Wed Jan 22 2014 12:41:09 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ullamco esse dolor aliquip ex incididunt voluptate reprehenderit. Ut nostrud nisi exercitation magna laborum labore aute. Mollit eiusmod eiusmod dolor nisi.",
            "title": "consectetur minim consequat incididunt officia voluptate consectetur ullamco",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Ellis Wilkerson",
            "ticketId": 172,
            "_id": 72
        },
        {
            "created_at": "Sun Jan 25 2015 02:41:11 GMT+0000 (UTC)",
            "status": "open",
            "description": "Consequat velit sint aute laborum reprehenderit culpa labore. Duis mollit irure ea elit minim ut nostrud in occaecat sunt. Do ea eu mollit est. Amet commodo quis cupidatat adipisicing tempor.",
            "title": "enim culpa do reprehenderit et eiusmod cupidatat mollit",
            "priority": "High",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Janis Morrow",
            "ticketId": 173,
            "_id": 73
        },
        {
            "created_at": "Fri Feb 21 2014 23:21:52 GMT+0000 (UTC)",
            "status": "open",
            "description": "Non fugiat mollit excepteur occaecat. Minim voluptate est cillum voluptate et duis. Voluptate dolore do amet tempor deserunt est. Commodo aute ex ad sunt et. Anim cillum irure aute proident occaecat pariatur laboris do consequat ad incididunt laborum pariatur.",
            "title": "irure laboris consectetur culpa elit est irure minim",
            "priority": "Medium",
            "problemType": "Software",
            "department": "HR",
            "userName": "Robinson Rollins",
            "ticketId": 174,
            "_id": 74
        },
        {
            "created_at": "Sun Mar 02 2014 22:07:45 GMT+0000 (UTC)",
            "status": "open",
            "description": "Anim et ad ipsum laborum deserunt ex minim dolor dolore sunt incididunt. Veniam ut ea exercitation veniam laboris officia quis velit culpa in. Ut labore anim officia deserunt sunt do dolor.",
            "title": "sint fugiat aute excepteur id consectetur ullamco velit",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Schneider Barrera",
            "ticketId": 175,
            "_id": 75
        },
        {
            "created_at": "Fri Jun 26 2015 22:25:58 GMT+0000 (UTC)",
            "status": "open",
            "description": "Labore sint Lorem ut laboris consequat id. Esse aute proident aliqua consectetur elit adipisicing consequat sint nisi aliqua magna deserunt eu. Incididunt nostrud exercitation elit ullamco ad cillum in. Cupidatat irure nostrud officia irure culpa anim cupidatat sint excepteur ut ullamco exercitation sint cillum. Id aliquip quis ex anim dolor labore cupidatat sint. Non consectetur cillum ex quis commodo duis occaecat fugiat duis duis proident.",
            "title": "eu esse dolore elit in veniam reprehenderit culpa",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Michelle Spencer",
            "ticketId": 176,
            "_id": 76
        },
        {
            "created_at": "Sat Jul 26 2014 01:55:52 GMT+0000 (UTC)",
            "status": "open",
            "description": "Nisi veniam dolor irure sint. Magna qui nostrud aute ex culpa velit nulla deserunt cillum culpa. In eu consequat consectetur elit in anim. Sunt cillum irure et aliqua laborum aliquip non minim cupidatat pariatur sit reprehenderit nostrud. Culpa Lorem id minim amet cupidatat.",
            "title": "adipisicing veniam laborum nulla reprehenderit voluptate pariatur ullamco",
            "priority": "High",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Eddie Dyer",
            "ticketId": 177,
            "_id": 77
        },
        {
            "created_at": "Tue Jun 17 2014 11:01:37 GMT+0000 (UTC)",
            "status": "open",
            "description": "Eiusmod reprehenderit sint officia consequat ullamco enim laboris velit. Ut qui sunt irure dolore. Eu qui enim exercitation fugiat et amet officia ex sunt cupidatat pariatur. Ipsum dolore incididunt quis sint aliquip aliqua amet veniam do.",
            "title": "id ex commodo occaecat mollit laborum nulla duis",
            "priority": "Low",
            "problemType": "Network",
            "department": "Marketing",
            "userName": "Mayra Anderson",
            "ticketId": 178,
            "_id": 78
        },
        {
            "created_at": "Tue May 12 2015 21:04:48 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ullamco nisi reprehenderit fugiat minim qui deserunt exercitation consectetur elit ut laboris elit adipisicing incididunt. Adipisicing dolor sunt sunt et laboris aute. Veniam amet aliquip consectetur eu laborum. Voluptate excepteur nulla commodo dolor do eu irure ad. Sit non et culpa excepteur aliquip minim ea esse proident cupidatat occaecat amet Lorem.",
            "title": "enim exercitation nulla ut qui qui sint velit",
            "priority": "Low",
            "problemType": "Software",
            "department": "IT",
            "userName": "Dollie Odonnell",
            "ticketId": 179,
            "_id": 79
        },
        {
            "created_at": "Thu Apr 03 2014 17:11:08 GMT+0000 (UTC)",
            "status": "open",
            "description": "Do irure deserunt ipsum aliqua consequat cillum duis esse. Ea eiusmod est magna voluptate duis Lorem excepteur reprehenderit. Cupidatat nulla qui Lorem amet officia esse labore Lorem sunt. Exercitation pariatur et adipisicing ullamco ea.",
            "title": "aute id duis proident incididunt anim velit magna",
            "priority": "Low",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Holcomb England",
            "ticketId": 180,
            "_id": 80
        },
        {
            "created_at": "Sat Sep 20 2014 23:13:18 GMT+0000 (UTC)",
            "status": "open",
            "description": "Laborum tempor ut id nostrud ea reprehenderit occaecat. Commodo esse do exercitation tempor consectetur sint id voluptate incididunt pariatur magna veniam culpa labore. Irure aliqua id id sint quis cupidatat ullamco ad exercitation ea adipisicing irure veniam.",
            "title": "proident duis adipisicing qui proident Lorem exercitation eu",
            "priority": "High",
            "problemType": "Network",
            "department": "Marketing",
            "userName": "Soto Larsen",
            "ticketId": 181,
            "_id": 81
        },
        {
            "created_at": "Sun Aug 30 2015 00:01:54 GMT+0000 (UTC)",
            "status": "open",
            "description": "Est ad proident sunt nisi deserunt aliquip sunt quis pariatur. Officia qui qui pariatur id quis irure anim tempor nostrud nulla. Minim labore ut minim voluptate laboris fugiat officia magna anim adipisicing laboris.",
            "title": "adipisicing ut pariatur laboris ex pariatur et laboris",
            "priority": "High",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Latonya Cochran",
            "ticketId": 182,
            "_id": 82
        },
        {
            "created_at": "Tue Nov 11 2014 10:48:21 GMT+0000 (UTC)",
            "status": "open",
            "description": "Enim ad culpa sit cillum eiusmod anim ipsum duis voluptate. Non Lorem consectetur adipisicing amet elit aliquip eu ad cupidatat. Eiusmod labore et sint mollit nostrud id qui laboris laboris consectetur commodo sunt enim eu. Esse amet ipsum ullamco irure mollit laboris qui proident occaecat irure dolore ipsum sit labore. Commodo excepteur duis cupidatat sunt dolore anim sint.",
            "title": "irure adipisicing mollit voluptate veniam veniam Lorem elit",
            "priority": "High",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Kaye Vargas",
            "ticketId": 183,
            "_id": 83
        },
        {
            "created_at": "Thu May 21 2015 21:09:07 GMT+0000 (UTC)",
            "status": "open",
            "description": "Sit ad sint aliqua quis. Consectetur elit amet officia enim pariatur Lorem voluptate veniam occaecat velit ex. Mollit mollit id pariatur aliqua Lorem nisi non culpa aliqua velit ex esse sunt. Id adipisicing ea do ad non quis nostrud sunt do veniam qui officia consectetur dolore.",
            "title": "esse amet voluptate velit commodo eiusmod consequat dolor",
            "priority": "High",
            "problemType": "Network",
            "department": "HR",
            "userName": "Sherman Meyers",
            "ticketId": 184,
            "_id": 84
        },
        {
            "created_at": "Wed Apr 22 2015 04:05:48 GMT+0000 (UTC)",
            "status": "open",
            "description": "Reprehenderit sint incididunt ex aliquip ipsum eu ea. Excepteur enim occaecat deserunt minim quis laborum mollit velit do mollit mollit ad. Occaecat veniam id eu laborum.",
            "title": "eu ex eiusmod dolor consectetur duis exercitation excepteur",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Poole Moss",
            "ticketId": 185,
            "_id": 85
        },
        {
            "created_at": "Mon Mar 09 2015 21:52:32 GMT+0000 (UTC)",
            "status": "open",
            "description": "Pariatur excepteur qui nostrud Lorem labore exercitation exercitation irure id pariatur nostrud eiusmod dolor elit. Duis tempor qui et excepteur excepteur nostrud dolor aute aute. Nisi eu velit nostrud fugiat nulla duis sint eu velit et irure ut anim. Commodo sint officia minim do est.",
            "title": "anim irure culpa voluptate officia excepteur esse ipsum",
            "priority": "Medium",
            "problemType": "Network",
            "department": "HR",
            "userName": "Dennis Dennis",
            "ticketId": 186,
            "_id": 86
        },
        {
            "created_at": "Thu Feb 19 2015 21:31:58 GMT+0000 (UTC)",
            "status": "open",
            "description": "Qui reprehenderit fugiat dolor velit est duis cillum ea. Velit labore ipsum deserunt ea dolore aute nulla. Magna deserunt id aliquip veniam incididunt ea excepteur sunt est aliquip occaecat. Aliqua occaecat consectetur nostrud reprehenderit Lorem irure. Aute duis excepteur ut ullamco aute aliqua laboris labore consequat voluptate nulla. In qui quis sunt aliquip dolor esse dolore.",
            "title": "qui velit magna minim aute consectetur consequat exercitation",
            "priority": "Medium",
            "problemType": "Network",
            "department": "HR",
            "userName": "Benson Whitfield",
            "ticketId": 187,
            "_id": 87
        },
        {
            "created_at": "Wed Nov 26 2014 02:43:40 GMT+0000 (UTC)",
            "status": "open",
            "description": "Aliquip ut aliquip ullamco aliquip fugiat esse enim dolor ipsum mollit culpa sit proident. Id dolor adipisicing est culpa. Fugiat aute veniam excepteur reprehenderit.",
            "title": "et proident laborum nisi esse nulla culpa id",
            "priority": "High",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Clayton Douglas",
            "ticketId": 188,
            "_id": 88
        },
        {
            "created_at": "Sun Apr 20 2014 21:43:12 GMT+0000 (UTC)",
            "status": "open",
            "description": "Dolor commodo velit aute pariatur sint adipisicing id. Velit voluptate voluptate elit quis officia labore id anim excepteur Lorem. Irure deserunt labore nulla exercitation. Exercitation et velit aute occaecat laboris occaecat anim ad esse. Laboris fugiat tempor sit occaecat laborum occaecat cillum.",
            "title": "adipisicing culpa occaecat ullamco reprehenderit est pariatur Lorem",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Nell Cook",
            "ticketId": 189,
            "_id": 89
        },
        {
            "created_at": "Fri Aug 14 2015 07:53:58 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ea laboris dolore aute culpa adipisicing. Est quis ex occaecat pariatur. Exercitation mollit incididunt ea mollit officia aute dolore nulla adipisicing.",
            "title": "elit magna id Lorem officia do id officia",
            "priority": "High",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Bond Yang",
            "ticketId": 190,
            "_id": 90
        },
        {
            "created_at": "Thu Jan 30 2014 13:00:03 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ea nostrud quis qui eiusmod aliquip qui est. Aliquip quis magna eu do consequat laborum aute aute id qui incididunt. Tempor adipisicing consectetur anim labore nulla veniam pariatur reprehenderit fugiat labore aliquip occaecat culpa. In deserunt quis sint est culpa. Eiusmod nisi ullamco aliquip sit veniam anim tempor amet culpa dolor magna.",
            "title": "proident eu excepteur consequat duis ad veniam velit",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "IT",
            "userName": "Charlotte Parker",
            "ticketId": 191,
            "_id": 91
        },
        {
            "created_at": "Sat Jul 05 2014 17:03:09 GMT+0000 (UTC)",
            "status": "open",
            "description": "Et ea culpa velit consequat tempor voluptate Lorem et. Pariatur mollit velit reprehenderit est fugiat officia exercitation irure magna pariatur. Deserunt elit anim officia labore.",
            "title": "culpa minim exercitation veniam deserunt nostrud minim labore",
            "priority": "Low",
            "problemType": "Network",
            "department": "HR",
            "userName": "Macdonald Blake",
            "ticketId": 192,
            "_id": 92
        },
        {
            "created_at": "Tue Jul 28 2015 02:12:51 GMT+0000 (UTC)",
            "status": "open",
            "description": "Culpa anim minim eiusmod dolor mollit ullamco aute excepteur pariatur reprehenderit duis pariatur. Eu ex tempor adipisicing irure enim minim ex pariatur ex tempor Lorem. Duis laboris laboris elit commodo elit ea adipisicing sint ea.",
            "title": "proident adipisicing cupidatat magna eu ipsum consectetur amet",
            "priority": "High",
            "problemType": "Software",
            "department": "Marketing",
            "userName": "Mann Galloway",
            "ticketId": 193,
            "_id": 93
        },
        {
            "created_at": "Mon Jun 29 2015 06:45:14 GMT+0000 (UTC)",
            "status": "open",
            "description": "Nulla ut dolor reprehenderit officia non cupidatat dolore velit dolor cillum cillum fugiat Lorem officia. Deserunt id fugiat in proident fugiat nulla quis cupidatat excepteur in eu non ullamco. Ex velit nisi sit ex mollit ea pariatur duis sit aute dolor nulla.",
            "title": "anim veniam excepteur amet proident velit occaecat dolor",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Burnett Hartman",
            "ticketId": 194,
            "_id": 94
        },
        {
            "created_at": "Mon Aug 04 2014 07:35:50 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ipsum fugiat ad commodo fugiat qui ut id tempor reprehenderit nostrud aute qui. Ullamco in quis id est ullamco tempor. Minim nisi incididunt veniam et nostrud exercitation culpa consectetur occaecat enim consectetur proident id. Laborum eiusmod do Lorem anim ea reprehenderit cillum ut nostrud dolore. Elit mollit anim culpa consectetur laborum eu exercitation laboris commodo.",
            "title": "non veniam ut labore fugiat anim magna minim",
            "priority": "Medium",
            "problemType": "Hardware",
            "department": "HR",
            "userName": "Potter Campbell",
            "ticketId": 195,
            "_id": 95
        },
        {
            "created_at": "Fri Jul 31 2015 05:04:00 GMT+0000 (UTC)",
            "status": "open",
            "description": "Lorem incididunt tempor dolore aliqua proident cupidatat est excepteur proident excepteur voluptate fugiat fugiat pariatur. Laborum sint amet est nisi. Cillum duis irure dolore aliqua. Exercitation excepteur laborum mollit veniam dolor voluptate dolore.",
            "title": "Lorem fugiat ex sit ullamco sunt non eiusmod",
            "priority": "High",
            "problemType": "Software",
            "department": "IT",
            "userName": "Huff Stokes",
            "ticketId": 196,
            "_id": 96
        },
        {
            "created_at": "Wed Apr 30 2014 15:02:15 GMT+0000 (UTC)",
            "status": "open",
            "description": "Eu deserunt ullamco dolor dolor tempor nisi et laborum laborum nulla. Velit mollit velit cillum officia est minim mollit proident. Aute duis ea pariatur voluptate Lorem nisi fugiat cupidatat nisi labore ex exercitation. Irure laboris minim proident nulla eu eu aute ipsum magna id sint ullamco in. Velit mollit sunt non esse Lorem cupidatat sit labore officia proident anim cupidatat. Elit quis est nisi excepteur Lorem sunt. Nostrud sint et consectetur nostrud cillum magna ea laborum incididunt ut exercitation Lorem ut sunt.",
            "title": "do aliquip dolore aliquip tempor qui amet deserunt",
            "priority": "Low",
            "problemType": "Network",
            "department": "HR",
            "userName": "Chaney Chang",
            "ticketId": 197,
            "_id": 97
        },
        {
            "created_at": "Fri Feb 06 2015 03:21:51 GMT+0000 (UTC)",
            "status": "open",
            "description": "Nulla et tempor occaecat eu et occaecat. Officia sit culpa nulla minim officia labore esse pariatur et est pariatur ad est laborum. Sunt culpa ullamco ad ut esse sunt.",
            "title": "proident do ex proident id minim cillum ut",
            "priority": "Medium",
            "problemType": "Network",
            "department": "HR",
            "userName": "Morrison York",
            "ticketId": 198,
            "_id": 98
        },
        {
            "created_at": "Sat May 09 2015 10:26:28 GMT+0000 (UTC)",
            "status": "open",
            "description": "Ut incididunt ut ea velit ex ad sunt mollit qui elit do. Est voluptate cillum adipisicing ut. Cillum Lorem adipisicing sunt incididunt do qui fugiat esse excepteur labore. Exercitation tempor est esse officia culpa est anim qui. Excepteur excepteur voluptate id qui et velit id esse sint magna Lorem tempor. Ex anim culpa id ipsum ullamco est nostrud. Nostrud culpa enim irure adipisicing sunt culpa ipsum exercitation ad sunt laborum ex do mollit.",
            "title": "officia esse eu nostrud tempor labore eu et",
            "priority": "High",
            "problemType": "Hardware",
            "department": "Marketing",
            "userName": "Dunlap Lester",
            "ticketId": 199,
            "_id": 99
        }
    ]




// Insert Data
Ticket.collection.insert(TicketData, onInsert);

// Insert function
function onInsert(err, docs){
    if(err){
        console.log('ERROR' + err);
    }else{
        console.log('Insert Success!')
    }
}

//http://mongoosejs.com/docs/index.html
// http://stackoverflow.com/questions/16726330/mongoose-mongodb-batch-insert
//db.getCollection('profiles').find().sort({firstName: 1})
//http://www.json-generator.com/